services:
  dnd-character-manager:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: dnd_character_manager_web
    ports:
      - "8010:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
